# Generated by Django 3.2.15 on 2022-10-08 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221008_2159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_website',
            new_name='social_facebook',
        ),
    ]
