# Generated by Django 3.2.15 on 2022-10-08 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_social_website_profile_social_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='fav_food',
        ),
    ]
