# Generated by Django 3.2.15 on 2022-10-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
